---
title: "PROJECT: kern-public-sector-employment"
author: "Rich Ryan"
email: "richryan@csub.edu"
format: gfm
---

## Public-sector employment in Kern County, California

How many public-sector jobs are there in Kern County, California?
This question is answered using data from the Quarterly Census of Employment and Wages.

## Data on public-sector employment in Kern County, California

## Posit Cloud and GitHub

The project was completed using Posit Cloud.
If you are interested in interacting with GitHub using Posit Cloud,
then these notes may be useful to you.

Here is the procedure I used to interact with GitHub through Posit Cloud:

* Create a [fine-grained personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens).
  * In the upper-right corner of any page on GitHub, click your profile photo, then click **Settings**
  * In the left sidebar, click **Developer** settings (at the bottom).
  * In the left sidebar, under **Personal access tokens**, click **Fine-grained tokens**.
  * Click **Generate new token**.
  * Under **Token name**, enter a name for the token.
  * Under **Expiration**, select an expiration for the token.
  * Optionally, under **Description**, add a note to describe the purpose of the token.
* Save the personal access token using `gitcreds::gitcreds_set()`.
* Check the configuration of credentials: `git config -- list`.
Confirm that credentials are stored.
(And perhaps run `git config --global credential.helper store`.)

These steps should let Posit Cloud push and pull from GitHub.
  
## API key in .Renviron

Data are retrieved from [FRED](https://fred.stlouisfed.org/) using their API (Application Programming Interface) service.
Using the service requires registering an API key with FRED.
The API key can then be saved in the `.Renviron` file.

* Include `FRED_API_KEY=my-api-key` in the `.Renviron` file using the command
`usethis::edit_r_environ()`.
* Restart the R session.
